# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# junk.py
# Created on: 2015-04-13 14:06:14.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Local variables:
major_roads = "C:\\Users\\Todd\\Desktop\\morepython\\tabletesting.gdb\\major_roads"
tracts = "C:\\Users\\Todd\\Desktop\\morepython\\tabletesting.gdb\\tracts"
major_roads_Buffer = "C:\\Users\\Todd\\Desktop\\morepython\\tabletesting.gdb\\major_roads_Buffer"
tracts_Clip = "C:\\Users\\Todd\\Desktop\\morepython\\tabletesting.gdb\\tracts_Clip"

# Process: Buffer
arcpy.Buffer_analysis(major_roads, major_roads_Buffer, "10000 Meters", "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Clip
arcpy.Clip_analysis(tracts, major_roads_Buffer, tracts_Clip, "")

rows = arcpy.UpdateCursor(tracts_Clip)
for row in rows:   
    if row.pctbelowpo < 10:
        rows.deleteRow(row)

