# ---------------------------------------------------------------------------
# update_row.py
# Created on: Tue May 10 2005 02:00:34 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import arcpy

# Local variables...
major_roads = "C:\\Users\\Todd\\Desktop\\morepython\\tabletesting.gdb\\major_roads"
tracts = "C:\\Users\\Todd\\Desktop\\morepython\\tabletesting.gdb\\tracts"
road_buffer = "C:\\Users\\Todd\\Desktop\\morepython\\tabletesting.gdb\\road_buffer"
clipped_tracts = "C:\\Users\\Todd\\Desktop\\morepython\\tabletesting.gdb\\clipped_tracts"
clipped_tracts__2_ = "C:\\Users\\Todd\\Desktop\\morepython\\tabletesting.gdb\\clipped_tracts"

# Process: Buffer...
gp.Buffer_analysis(major_roads, road_buffer, "10000.000000 Meters", "FULL", "ROUND", "ALL", "")

# Process: Clip...
gp.Clip_analysis(tracts, road_buffer, clipped_tracts, "")

#******************************
#UPDATE_CURSOR using UPDATE_ROW
#******************************

# Process: Add Field...
gp.AddField_management(clipped_tracts, "NEW_CLASS", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

rows = arcpy.UpdateCursor(clipped_tracts)
for row in rows:
    if row.pctbelowpo < 20:
        row.new_class = 1
    elif row.pctbelowpo >= 20 and row.pctbelowpo < 40:
        row.new_class = 2
    elif row.pctbelowpo >= 40 and row.pctbelowpo < 60:
        row.new_class = 3
    elif row.pctbelowpo >= 60 and row.pctbelowpo < 80:
        row.new_class = 4
    elif row.pctbelowpo >= 80 and row.pctbelowpo < 100:
        row.new_class = 5
    elif row.pctbelowpo >= 100:
        row.new_class = 6
    rows.UpdateRow(row)


